# Generated by Django 4.2.2 on 2023-06-11 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ["expected_return_date"]},
        ),
    ]
